imports:
    - { resource: config.yml }
    - { resource: database.php }

twig:
#    cache: true

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#snc_redis:
#    clients:
#        default:
#            type: predis
#            alias: default
#            dsn: "%redis_dsn%"
#        doctrine:
#            type: predis
#            alias: doctrine
#            dsn: "%redis_dsn%"
#    doctrine:
#        metadata_cache:
#            client: doctrine
#            entity_manager: default
#            document_manager: default
#        result_cache:
#            client: doctrine
#            entity_manager: [default]
#        query_cache:
#            client: doctrine
#            entity_manager: default

doctrine:
    orm:
#        metadata_cache_driver: redis
#        query_cache_driver: redis
#       result_cache_driver: redis

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path: "php://stderr"
            level: debug
        console:
            type:  console
