imports:
    - { resource: config.yml }
    - { resource: database.php }
    - { resource: email.php }
    - { resource: queue.php }

twig:
#    cache: true

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            host: %redis_host%
            user: %redis_user%
            port: %redis_port%
            password: %redis_password%
            database: %redis_database%
    session:
        client: default
        prefix: session
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default
            document_manager: default
        result_cache:
            client: default
            entity_manager: default
        query_cache:
            client: default
            entity_manager: default
    monolog:
        client: monolog
        key: monolog
#            document_manager: default
#        result_cache:
#            client: doctrine
#            entity_manager: [default]
#        query_cache:
#            client: doctrine
#            entity_manager: default

doctrine:
    orm:
#        metadata_cache_driver: redis
#        query_cache_driver: redis
#       result_cache_driver: redis

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path: "php://stderr"
            level: debug
        console:
            type:  console
