imports:
    - { resource: config.yml }
    - { resource: database.php }
    - { resource: email.php }

twig:
#    cache: true

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc
#            document_manager: default
#        result_cache:
#            client: doctrine
#            entity_manager: [default]
#        query_cache:
#            client: doctrine
#            entity_manager: default

doctrine:
    orm:
#        metadata_cache_driver: redis
#        query_cache_driver: redis
#       result_cache_driver: redis

old_sound_rabbit_mq:
    connections:
        consumer:
            host:     trapped-scabious-18.bigwig.lshift.net
            port:     10107
            user:     DDEZ0jmd
            password: PLcITWMS8eHh0SfDEfYkcIWb6l3qHElr
            vhost:    VF2y3yEBBeeU
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0
        producer:
            host:     trapped-scabious-18.bigwig.lshift.net
            port:     10106
            user:     DDEZ0jmd
            password: PLcITWMS8eHh0SfDEfYkcIWb6l3qHElr
            vhost:    VF2y3yEBBeeU
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path: "php://stderr"
            level: debug
        console:
            type:  console
