imports:
    - { resource: config.yml }
    - { resource: database.php }
    - { resource: email.php }

framework:
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  snc_redis.session.handler

twig:
#     cache: "%kernel.cache_dir%/twig"

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc
#            document_manager: default
#        result_cache:
#            client: doctrine
#            entity_manager: [default]
#        query_cache:
#            client: doctrine
#            entity_manager: default

doctrine:
    orm:
#        metadata_cache_driver: redis
#        query_cache_driver: redis
#       result_cache_driver: redis

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://pshu5i6veq67rdd4mvcn7mqt@ec2-54-83-9-36.compute-1.amazonaws.com:15169
    session:
        client: default
        prefix: bb
#    doctrine:
#        metadata_cache:
#            client: default
#            entity_manager: default
#            document_manager: default
#        result_cache:
#            client: default
#            entity_manager: [default, read]
#            document_manager: [default, slave1, slave2]
#            namespace: "dcrc:"
#        query_cache:
#            client: default
#            entity_manager: default

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path: "php://stderr"
            level: debug
        console:
            type:  console
