imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

twig:
    cache: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info
assetic:
  filters:
    cssrewrite: ~
    sass: ~
    compass: ~
  use_controller: true
#windows-only config
#  ruby: C:\Ruby22\bin\ruby.exe
#  sass: C:\Ruby22\bin\sass.bat
#  filters:
#    cssrewrite: ~
#    sass:
#      bin: C:\Ruby22\bin\sass
#      apply_to: "\.scss$"
#    compass:
#      bin: C:\Ruby22\bin\compass
#  use_controller: false

#swiftmailer:
#    delivery_address: me@example.com
