app:
    resource: "@AppBundle/Controller/"
    type:     annotation
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
survey:
    path: /survey
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: https://www.surveymonkey.com/r/BiBeauty
        permanent: true
