sonata_seo:
    page:
        title: BiBeauty
        metas:
            name:
                description: Awesome BiBeauty
                keywords: beauty culture, appointments, bookings, bibeauty, last minute, los angeles
            property:
                'og:site_name': BiBeauty
                'og:description': Awesome BiBeauty
                'og:image': 'https://www.bibeauty.com/assets/images/feature_banner.jpg'
