# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    aws:
        version: 'latest'
        region: 'us-west-1'
        bucket: 'bibeauty-dev'
        credentials:
            key: 'AKIAIBIIEKOCJZS4Y2HA'
            secret: '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'
    braintree:
        version: 'latest'
    yelp:
        consumer_key: '-S2PvM-f9LLrDjGJgsi-Fw'
        consumer_secret: 'NjoaIcbHauneS1VA4vO9gMll3Vo'
        token: '8K4AQnikVYMd1hxzfLQWETpUFaaxZHqa'
        token_secret: 'r18hQFFO0SC15F14svVeH_vRhTU'
#        api_host: 'api.yelp.com'
    twilio:
        account_sid: AC2ddd561109c7c215d8b5504dbfa89bc3
        auth_token: ef117c3bbe875056ad32ac5307186081
        phone_number: 6506811823

services:
    kernel.listener.superadmin:
        class: AppBundle\EventListener\AdminAwareListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    aws.factory:
        class: AppBundle\Services\AWSFactory
        arguments: ["%aws%", @logger]
    mailer.factory:
        class: AppBundle\Services\Mailer
        arguments: [@mailer, @templating, @logger]
    braintree.factory:
        class: AppBundle\Services\BraintreeFactory
        arguments: ["%braintree%", @logger]
    yelp.factory:
        class: AppBundle\Services\YelpFactory
        arguments: ["%yelp%", @logger]
    create_availabilities_service:
        class: AppBundle\Consumer\CreateAvailabilities
        arguments: ['@service_container']
    twilio.factory:
        class: AppBundle\Services\TwilioFactory
        arguments: ["%twilio%", @logger]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments: ["%aws%"]
        tags:
            - { name: twig.extension }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
