<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use AppBundle\Entity\ServiceType;
use AppBundle\Entity\ServiceCategory;


class LoadServiceTypeData implements OrderedFixtureInterface
{

    private $serviceTypes  = array(
        "Hair" => array(
            "Haircuts and Hairdressing ",
            "Blow dry",
            "Hair colouring and Highlights Treatments ",
            "Mens Haircuts and Hairdressing ",
            "Hair conditioning and Scalp treatments",
            "Hair consulting ",
            "Brazilian blow dry and Dry keratin treatment ",
            "Balayage ",
            "Ombre ",
            "Hairstyling and Updos",
            "Afro hairdressing ",
            "Hair extensions",
            "Permanent waves",
            "Straighteners ",
            "Chemical relaxing ",
            "Braids ",
            "Locs",
            "Wedding Hair",
            "Japanese Straightening ",
            "Hair transplants ",
            "Hair loss treatments - non surgical  ",
            "Airlites",
            "Brocato's smoothing system ",
            "Granny hair",
            "Pastel hair",
        ),
            "Hair Removal" => array(
            "Waxing ",
            "Hollywood waxing ",
            "Brazilian waxing ",
            "Threading ",
            "French Bikini Wax",
            "Male waxing",
            "Vajazzling ",
            "Depilation",
            "Laser Hair removal",
            "Epilar ",
            "Sugaring ",
            "Intense Pulsed Light Therapy (IPL)",
            "Electrolysis",
            "Soprano Laser Hair Removal",
            "Beard trimming ",
            "Men's shaving ",
            "Ear Hair Trimming ",
            "Nasal hair trimming ",
            "Shaving lesson ",
        ),
        "Massage"=> array(
            "Deep tissue massage",
            "Swedish Massage",
            "Theraputic massage",
            "Thai massage",
            "Aromatherapy massage",
            "Stone massage therapy",
            "Indian head massage ",
            "Sports massage",
            "Foot massage",
            "Reflexology",
            "Face massage",
            "Pre and Post Natal massage",
            "Hand massage ",
            "Chair massage",
            "Lymphatic drainage ",
            "Biodynamic massage ",
            "Tui Na Massage ",
            "Lava Shells Massage",
            "Acupressure ",
            "Trigger point therapy ",
            "Hot candle massage",
            "Abhyanga Ayurvedic massage",
            "Balanise massage",
            "Lomi Lomi massage",
            "Bamboo massage",
            "Herbal Compress Massage",
            "Turkish Bath",
            "Four hands massage",
            "Himalayan mineral massage ",
            "Neuromuscular massage therapy",
            "Honey massage",
            "Chakra massage ",
            "Hydrotherm massage",
            "Children's massage",
            "Thai Luk Pra Kob massage ",
            "Abdominal massage ",
            "Scar tissue massage",
            "Garshan ",
            "Sound massage",
            "MELT Method",
            "Chi Nei Tsang",
            "Chavutti Thirumal Massage",
            "Baobab Massage",
            "Esalen Massage",
            "Lava Bambu massage",
            "Ashiatsu",
            "No hands Massage",
            "Seitai massage",
            "Six hand massage",
            "Watsu massage",
            "Srota Ayurvedic massage",
            "Underwater massage",
            "Rollerssage",
            "Vishesh Ayurvedic massage",
        ),
        "Nails" => array(
            "Gel nails ",
            "Pedicure",
            "Manicure",
            "Two week manicure ",
            "Nail extensions & overlays ",
            "Two week pedicure ",
            "Foot scrub",
            "Nail art",
            "Callus peel ",
            "Praffin Wax treatments",
            "Minx nails ",
            "Swarovski Crystal Pedicure/Manicure ",
            "Fish pedicure ",
            "Perfect Sense Paraffin Wax",
            "Snakeskin manicure ",
            "Fish Manicure",
        ),
        "Face"=>array(
            "Facials",
            "Eyebrow and Eyelash Treatments ",
            "Eyelash extensions ",
            "HD Brows ",
            "Microdermabrasion ",
            "Eyebrow and Eyelash tinting ",
            "Eyebrow threading",
            "Eye treatments",
            "Eyebrow waxing ",
            "Mens facial",
            "Makeup treatments",
            "LVL Lashes ",
            "Facials - CACI",
            "Beauty treatments",
            "Chemical Skin Peel",
            "Face lift - nonsurgical ",
            "Skincare consultation",
            "Acne Treatements",
            "Eyelash Perming ",
            "Makeover Experiences",
            "Oxygen Facial ",
            "Permanent and Semi Permanent Makeup Treatments",
            "24 Carat Gold Facial ",
            "Billion Dollar Brows",
            "Teen facials ",
            "Facials - Galvanic ",
            "Micro-Needling ",
            "LED Light Therapy",
            "Microcurrent Face & Body Treatments",
            "Facial Reflexology ",
            "Semi Permanent Mascara ",
            "Wedding make-up",
            "Foto Facial RF Skin Rejuvination",
            "Brow Lift",
            "Facial Rejuvination Acupuncture ",
            "Dermaplaning ",
            "LPG Facelift ",
            "Skin Peel",
            "Stem Cell Facial ",
            "Camouflage Make-up",
            "Placenta Facial ",
            "Snail Facial ",
            "Geisha Facial ",
            "Auricular Acupuncture ",
            "Honey Facial ",
            "Lava Shell Therma Facial",
        ),
        "Body"=> array(
            "Spray tanning and sunless tanning",
            "Body treatments",
            "Body exfoliation",
            "Body wraps",
            "Sunbeds and tanning booths ",
            "Colonic Hydrotherapy",
            "Cellulite treatements",
            "Acupuncture",
            "Backcials ",
            "Steam and sauna therapy",
            "Endermologie Lipo-massage",
            "Cryolipolysis",
            "Cupping",
            "Henna Designs and tattoos",
            "Laser Lipo",
            "Universal Contour wrap",
            "i-Lipo",
            "Heat treatments",
            "Infrared therapy",
            "Acoustic wave therapy",
            "Ultrasound therapy",
            "Multi Polar Radio Frequency therapy",
            "Rasul and mud treatments",
            "Body hair bleaching ",
            "Vinotherapy",
            "Cryotherapy",
            "Hydrotherapy",
            "VelaShape",
            "Arasys toning and Inch loss treatment ",
            "Iyashi dome ",
            "Photorejuvination treatments",
            "Tattooing ",
            "Body treatments - CACI",
            "Lipodissolve ",
            "Piercing ",
            "Sclerotherapy",
            "Gua Sha",
            "Sun angel",
            "Lipo-light",
            "Electrotherapy",
            "Strawberry Laser lipo",
            "24 carat gold body treatment",
            "SmartLipo",
            "Pre-birth acupuncture ",
            "Colonic therapy",
            "Akasuri",
            "Endermotherapy",
            "Bikini facial",
            "Russian Banya",
            "Hyperhidrosis treatment ",
            "Vaser lipo-contouring ",
            "Ne needle mesotherapy",
            "Floatation",
        ),
    );
    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        foreach($this->serviceTypes as $category => $types){
          $catid = $this->getCatIdByName($manager, $category);
          foreach($types as $type){
              $serviceType = new ServiceType();
              $serviceType->setLabel($type);
              $serviceType->setServiceCategoryId($catId);
              $manager->persist($serviceType);
          }
          $manager->flush();
        }
        $manager->flush();
    }
    public function getCatIdByName($em, $category){
        $records = $em->getRepository("AppBundle:ServiceCategory");
        $cat = $records->findOneBy(array('label' => $category));
        var_dump($cat);
        return $cat->getId();
    }
    public function getOrder()
    {
      return 2;
    }
}
