<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
    public function findBookingsByAvailability($day, $starttime = null,$endtime=null){
      $qb    = $this->createQueryBuilder('b');
      $query = $qb->select(['b','tas'])
         ->from('AppBundle:Booking', 'b')
         ->leftjoin('AppBunndle:TreatAvailabilitySet','tas');
      if($day !=null){
        $query->where('tas.day = :day')
              ->setParameter('day',$day);
      }
      if($startime !== null && $endtime !=null){
        $query->add('where',
            $qb->expr()->between(
                'tas.datefield',
                ':starttime',
                ':endtime'
            )
        )->setParameters(['starttime' => $starttime, 'endtime' => $endtime]);
      }else if($endtime !==null || $starttime !==null){
        $time = ($starttime === null) ? $endtime : $starttime;
        $query->andWhere('tas.time = :time')
              ->setParameter('time',$time);
      }
      $result=$query->getQuery()
                    ->getResult();
      return $result;
    }

    public function searchAvailability(){

    }
  //if()andWhere('r.winner IN (:ids)')  ->setParameter('ids', $ids);
}
