<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessRepository extends EntityRepository
{
  public function findBusinessByLocation($zip){
    $qb    = $this->createQueryBuilder('b');
    $query = $qb->select(['b','a'])
       //->from('AppBundle:Business', 'b')
       ->leftjoin('AppBundle:Address','a')
       ->where('a.zip = :zip')
       ->setParameter('zip',$zip);
    $result=$query->getQuery()
                  ->getResult();
    return $result;
  }

  public function findBusinessByService($serviceTypeId, $serviceCategoryId = null){
    $qb    = $this->createQueryBuilder('b');
    $query = $qb->select(['b','bk','s','st','sc'])
       ->leftJoin('AppBundle:Booking','bk')
       ->leftJoin('AppBundle:Service','s')
       ->leftJoin('AppBundle:ServiceType','st')
       ->leftjoin('AppBundle:ServiceCategory','sc')
       ->where('st.serviceTypeId = :serviceTypeId')
       ->setParameter('serviceTypeId',$serviceTypeId);
    if($serviceCategoryId !== null){
      $query->where('sc.serviceCategoryId = :ServiceCategoryId')
            ->setParameters('serviceCategoryId',$serviceCategoryId);
    }
    $result=$query->getQuery()
                  ->getResult();
    return $result;
  }

  public function findBusinessTreatmentsCategory($business)
  {
    $treatments = [];
    foreach($business->getTreatments() as $tx){
      $cat = $tx->getTreatmentCategory()->getCategoryName();
      $this->checkSetCatKey($tx, $cat, $treatments);
      $treatments[$cat][] = $tx;
    }
    return $treatments;
  }

  private function checkSetCatKey($tx,$cat,&$treatments)
  {
    if(!array_key_exists($cat, $treatments)){
      $treatments[$cat] = [];
    }
  }
}
