<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends EntityRepository
{
    public function recentDeals($limit = 3) {
            $qb = $this->createQueryBuilder('Offer');
            $qb
                ->from('AppBundle:Offer', 'o')
                ->leftJoin('o.business','b')
                ->leftJoin('b.address', 'ba')
                ->leftJoin('o.treatment', 't')
                ->setMaxResults(3);

            $query = $qb->getQuery();
            $results = $query->getResult();

            return $results;
    }

  //if()andWhere('r.winner IN (:ids)')  ->setParameter('ids', $ids);
}
