<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TreatmentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function bySearchTerm($term = '', $brands = array()) {
        /* This needs a ton of optimizaton */
        // @todo

        if (empty($term) && count($brands) < 1) {
            return $this->findAll();
        }

        $qb = $this->createQueryBuilder('p');

        if (!empty($term)) {

            $qb
                ->andWhere('p.name LIKE :term')
                ->setParameter('term', '%' . $term . '%')
                ;

        }

        if (count($brands) > 0) {
            $qb->andWhere('p.brand = :brands')
            ->setParameter('brands', $brands);
        }

        $query = $qb->getQuery();
        return $results = $query->getResult();

    }

}
