<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TreatmentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function bySearchTerm($term = '') {
        /* This needs a ton of optimizaton */
        // @todo

        if (empty($term)) {
            return $this->findAll();
        }

        $qb = $this->createQueryBuilder('p');
        $qb
            ->andWhere('p.name LIKE :term')
            ->setParameter('term', '%' . $term . '%');

        $query = $qb->getQuery();
        return $results = $query->getResult();

    }

}
