<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TreatmentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreatmentRepository extends EntityRepository
{
    public function updateAll($ids,$names,$times,$prices)
    {
        foreach($ids as $k => $id){
          $this->doUpdate($id,$names[$k],$times[$k],$prices[$k]);
        }
    }

    protected function doUpdate($id,$name,$time,$price){
      $qb = $this->createQueryBuilder('t');
      $qb->update("AppBundle:Treatment",'t')
          ->set('t.name', ':name')
          ->set('t.duration', ':time')
          ->set('t.originalPrice',':price')
          ->where('t.id = :id')
          ->setParameters([
              'name'=>$name,
              'time'=>$time,
              'price'=>$price,
              'id'=> $id
            ])
            //var_dump($qb->getQuery()->getSql());
          ->getQuery()
          ->execute();
    }

}
