<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TreatmentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreatmentCategoryRepository extends EntityRepository
{
    public function getHeirarchy() {
            $qb = $this->createQueryBuilder('TreatmentCategory');
            $qb
                ->from('AppBundle:TreatmentCategory', 'c')
                ->leftJoin('c.children','children')
                ->where('children.parent = c');

            $query = $qb->getQuery()
                ->getResult();

            return $query;
    }

}
