<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TreatmentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreatmentRepository extends EntityRepository
{
    public function findByBusiness(Business $business) {
        $qb    = $this->createQueryBuilder('t');

        $query = $qb
              ->addSelect('p.label')
              ->innerJoin('t.treatmentCategory','tc')
              ->innerJoin('tc.parent', 'p')
              ->where('t.business = :business')
              ->setParameter('business', $business);

        $treatments = $query->getQuery()->getResult();

        $cats = array();

        foreach($treatments as $treatmentData) {
            $treatment = $treatmentData[0];
            $label = $treatmentData['label'];

            if (!array_key_exists($label, $cats)) {
                $cats[$label] = array();
            }
            $cats[$label][] = $treatment;
        }

        return $cats;

    }

}
