<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TreatmentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreatmentCategoryRepository extends EntityRepository
{
    public function getHeirarchy() {
        /* This needs a ton of optimizaton */
        // @todo
        $categories = $this->findAll();

        $cats = array();
        foreach($categories as $category) {
            if ($category->getParent() === NULL) {
                $cats[] = $category;
            }
        }

        return $cats;

    }

}
