<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TreatmentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreatmentCategoryRepository extends EntityRepository
{
    public function getHeirarchy() {
        /* This needs a ton of optimizaton */
        // @todo
        $categories = $this->findAll();

        $cats = array();
        foreach($categories as $category) {
            if ($this->isCat($category)) {
                $cats[] = $category;
            }
        }

        return $cats;

    }
    public function findTreatmentsByCategory()
    {
      $treatments = $this->findAll();
      $txs        = [];
      foreach($treatments as $treatment) {
          if (!$this->isCat($treatment)) {
              $cat = $treatment->getParent();
              $cat = $cat->getLabel();
              $this->checkMakeCatKey($cat, $txs);
              $txs[$cat][] = $treatment;
          }
      }
      return $txs;
    }
    private function checkMakeCatKey($cat, &$txs)
    {
      if(!array_key_exists($cat, $txs)){
        $txs[$cat] = [];
      }
    }
    private function isCat($row)
    {
      return  ($row->getParent() === NULL) ? true : false;
    }

}
